all: tarea4.hs
	ghc -o tarea4 --make -ticky -rtsopts -threaded tarea4.hs

inocente: tareaInocente.hs
	ghc -o tareaInocente --make -threaded tareaInocente.hs

clean:
	$(RM) tarea4 tareaInocente *.hs~ *.o *.hi
